# Generated by Django 4.0.6 on 2022-07-07 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anger_iceberg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
