# Generated by Django 4.0.6 on 2022-07-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anger_iceberg_app', '0002_quote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
