# Generated by Django 4.0.4 on 2022-06-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
