# Generated by Django 4.0.6 on 2022-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('win_counter', models.IntegerField()),
                ('loss_counter', models.IntegerField()),
                ('detail', models.CharField(max_length=1000)),
                ('img_link', models.CharField(max_length=100)),
            ],
        ),
    ]
