# Generated by Django 4.0.6 on 2022-07-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='journalEntry',
        ),
    ]
