# Generated by Django 4.0.6 on 2022-07-27 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal_app', '0002_rename_todoitem_journalentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='loss_counter',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='password',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
