# Generated by Django 4.0.6 on 2022-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_remove_journalentry_loss_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='win_counter',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='result',
            field=models.IntegerField(),
        ),
    ]
