# Generated by Django 4.0.5 on 2022-07-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
