# Generated by Django 4.0.5 on 2022-07-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_list_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
