# Generated by Django 4.0.4 on 2022-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('created_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('completed_boolean', models.BooleanField()),
            ],
        ),
    ]
