# Generated by Django 4.0.4 on 2022-07-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
