# Generated by Django 4.0.6 on 2022-07-27 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone2_app', '0002_remove_email_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capstone2_app.claim'),
        ),
    ]
