# Generated by Django 4.0.6 on 2022-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone2_app', '0003_email_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='last_note_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
