# Generated by Django 4.0.5 on 2022-06-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
